.

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -2,9 +2,6 @@
 FROM node:22-alpine
 WORKDIR /app
 COPY . .
-RUN \
-   if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
-   else echo "Lockfile not found." && exit 1; \
-   fi
+RUN if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install --no-frozen-lockfile; else echo "Lockfile not found." && exit 1; fi
 EXPOSE 3001
 CMD ["node", "server.js"]
